name: Boutimar Travel
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5698066526092589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d4a8d'
    - '#b3bfd4'
    - '#00aded'
    - '#de914e'
  brandStrength: 0.492110043996945
  lightness: 1
  saturation: 0.8251711644697934
  rhythmicContrast: 0.8991572333034128
purpose: []
